server:
    port: 8080 #服务器用80端口
    servlet:

#log
logging:
    config: classpath:logback.xml
    root: debug
    level:
        com:
            netflix: warn
            dsmall: debug
        cn:
            px: debug
        org:
            springframework: warn
            apache: warn
spring:
    devtools:
        enabled: true
    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true
    freemarker:
        template-loader-path:
        - classpath:/templates
        - file:./templates
        cache: false
        checkTemplateLocation: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##
    rabbitmq:
        host: 106.13.55.232
        port: 5672
        username: admin
        password: admin
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    redis:
        #    cluster:
        #      nodes: 106.13.55.232:6379
        #      max-redirects: 5
        host: 106.13.55.232
        port: 6379
        timeout: 3000
        pool:
            max-active: 20
            max-idle: 5
            min-idle: 2
            max-wait: 2000
    session:
        store-type: redis
    datasource:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://106.13.55.232:3306/db_mblog?useSSL=false&characterEncoding=utf8
            username: root
            password: root

#        order00:
#            driver-class-name: com.mysql.jdbc.Driver
#            jdbc-url: jdbc:mysql://106.13.55.232:3306/ds_order_00?useUnicode=true&characterEncoding=utf8&useSSL=false
#            username: root
#            password: root
#            minimum-idle: 10
#            maximum-idle: 20
#            max-wait-millis: 10000
#            initial-size: 10
#        order01:
#            driver-class-name: com.mysql.jdbc.Driver
#            jdbc-url: jdbc:mysql://106.13.55.232:3306/ds_order_01?useUnicode=true&characterEncoding=utf8&useSSL=false
#            username: root
#            password: root
#            minimum-idle: 10
#            maximum-idle: 20
#            max-wait-millis: 10000
#            initial-size: 10
#        order02:
#            driver-class-name: com.mysql.jdbc.Driver
#            jdbc-url: jdbc:mysql://106.13.55.232:3306/ds_order_02?useUnicode=true&characterEncoding=utf8&useSSL=false
#            username: root
#            password: root
#            minimum-idle: 10
#            maximum-idle: 20
#            max-wait-millis: 10000
#            initial-size: 10
#        order03:
#            driver-class-name: com.mysql.jdbc.Driver
#            jdbc-url: jdbc:mysql://106.13.55.232:3306/ds_order_03?useUnicode=true&characterEncoding=utf8&useSSL=false
#            username: root
#            password: root
#            minimum-idle: 10
#            maximum-idle: 20
#            max-wait-millis: 10000
#            initial-size: 10

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.store.root}/indexes

    servlet:
        multipart:
            max-file-size: 5MB

    mail:
        host: smtp.mtons.com
        username: example@mtons.com
        password: Example2018
        port: 25
        properties:
            mail.smtp.auth: true

# site.theme: [default|card]
site:
    theme: card
    store:
      repo: absolute
      root: /data/mblog/
      size: 2
common:
    aliyun:
        sms:
            access-key-id:
            access-key-secret:
            sign-name:
            register-sms-template-code:
            login-sms-template-code:
            password-sms-template-code:
            #     设置短信验证码，此值设置后，所有验证码都为此值
            send-phone-code-sms: 999999
            #    短信验证码发送开关,false-不发短信；true-发送短信
            send-sms-flag: false
        oss:
            #文件上传大小，单位：M
            oss-image-size: 10
            bucket-name: dianyu-mblog
            http-url: https://dianyu-mblog.oss-cn-beijing.aliyuncs.com
            endpoint: https://oss-cn-beijing.aliyuncs.com
            access-key-id: LTAIqqFQEmdy6juv
            access-key-secret: mmDIPdf2JOwv4WjGbis8YQQtvKtS2P
    wxpay:
        appId: wxa617f1e7d1b2a223
        mchId: 1510733941
        key: F958555EB4D5E51226011B2012B07B4D
        notifyUrl: